#!/usr/bin/env bash
set -euo pipefail
unset PYTHONHOME
unset PYTHONPATH
unset PYTHONEXECUTABLE

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/TinManX1-arc-overhang.XXXXXX")"
trap 'rm -rf "$tmp_dir"' EXIT

arc_input="$tmp_dir/arc-input.gcode"
arc_output="$tmp_dir/arc-output.gcode"
arc_audit="$tmp_dir/arc-audit.json"
adapter_input="$tmp_dir/adapter-input.gcode"
adapter_audit="$tmp_dir/adapter-input.gcode.arc_support_audit.json"
support_input="$tmp_dir/support-input.gcode"
support_output="$tmp_dir/support-output.gcode"
support_audit="$tmp_dir/support-audit.json"
support_adapter_input="$tmp_dir/support-adapter-input.gcode"
support_adapter_audit="$tmp_dir/support-adapter-input.gcode.arc_support_audit.json"

cat >"$arc_input" <<'GCODE'
; generated by OrcaSlicer
; CONFIG_BLOCK_START
; nozzle_diameter = 0.4
; outer_wall_line_width = 0.4
; use_relative_e_distances = 1
; detect_overhang_wall = 1
; reduce_crossing_wall = 1
; filament_diameter = 1.75
; use_volumetric_e = 0
; CONFIG_BLOCK_END
M83
;LAYER_CHANGE
G1 X0 Y0 F9000
; FEATURE: Arc overhang
;TYPE:Arc infill
G1 X1 Y0 E0.04 F1200
G1 X2 Y0.4 E0.04 F1200
G1 X3 Y0.8 E0.04 F1200
;TYPE:Internal infill
G1 X3 Y1 F9000
GCODE

"$repo_root/scripts/orcaslicer_codex_arc_support_transform.py" \
  "$arc_input" "$arc_output" --audit "$arc_audit"

python3 - "$arc_input" "$arc_output" "$arc_audit" <<'PY'
import json
import pathlib
import sys

input_path = pathlib.Path(sys.argv[1])
output_path = pathlib.Path(sys.argv[2])
audit_path = pathlib.Path(sys.argv[3])
audit = json.loads(audit_path.read_text(encoding="utf-8"))
output = output_path.read_text(encoding="utf-8")

if input_path.read_text(encoding="utf-8") == output:
    raise SystemExit("Arc Overhang transform did not add guarded metadata")
if audit.get("status") != "ok":
    raise SystemExit(f"Arc Overhang audit failed: {audit}")
if audit.get("support_strategy") != "arc":
    raise SystemExit("Arc Overhang audit missing arc strategy")
if audit.get("base_support_path") != "bridge_overhang_generation":
    raise SystemExit("Arc Overhang audit should use bridge/overhang source geometry")
if audit.get("postprocess_stage") != "replace_bridge_infill_with_arc_overhangs":
    raise SystemExit("Arc Overhang audit has the wrong postprocess stage")
if audit.get("native_arc_support_enabled") is not False:
    raise SystemExit("Native support-to-arc conversion must remain disabled")
for marker in [
    "; orcaslicer_codex_arc_support_status=guarded_preview",
    "; orcaslicer_codex_arc_support_transform_status=ok",
    "; orcaslicer_codex_arc_support_strategy=arc",
    ";TYPE:Arc infill",
]:
    if marker not in output:
        raise SystemExit(f"Missing output marker: {marker}")
if ";TYPE:Arc support" in output or "; FEATURE: Arc support" in output:
    raise SystemExit("Arc Overhang output must not be classified as support material")
if "; tinmanx_arc_support_" in output:
    raise SystemExit("Output should use TinManX1 Arc Overhang markers")
if int(audit.get("after", {}).get("arc_infill_extrusion_moves", 0)) <= 0:
    raise SystemExit("Audit did not count Arc infill extrusion moves")
if int(audit.get("after", {}).get("arc_support_extrusion_moves", 0)) != 0:
    raise SystemExit("Audit should not count Arc support extrusion moves")
if int(audit.get("after", {}).get("normal_support_extrusion_moves", 0)) != 0:
    raise SystemExit("Arc Overhang output must not contain normal support extrusion moves")
PY

cp "$arc_input" "$adapter_input"
ORCASLICER_CODEX_ARC_SUPPORT_TRANSFORM="$repo_root/scripts/orcaslicer_codex_arc_support_transform.py" \
  "$repo_root/scripts/orcaslicer_codex_arc_support_inplace_adapter.py" \
  "$adapter_input"

python3 - "$adapter_input" "$adapter_audit" <<'PY'
import json
import pathlib
import sys

gcode_path = pathlib.Path(sys.argv[1])
audit_path = pathlib.Path(sys.argv[2])
gcode = gcode_path.read_text(encoding="utf-8")
audit = json.loads(audit_path.read_text(encoding="utf-8"))
if "; orcaslicer_codex_arc_support_transform_status=ok" not in gcode:
    raise SystemExit("In-place adapter did not replace the G-code with Arc Overhang output")
if ";TYPE:Arc support" in gcode:
    raise SystemExit("In-place adapter wrote support-classed arc output")
if audit.get("status") != "ok":
    raise SystemExit("In-place adapter audit is not ok")
PY

cat >"$support_input" <<'GCODE'
; generated by OrcaSlicer
; CONFIG_BLOCK_START
; nozzle_diameter = 0.4
; outer_wall_line_width = 0.4
; use_relative_e_distances = 1
; detect_overhang_wall = 1
; reduce_crossing_wall = 1
; filament_diameter = 1.75
; use_volumetric_e = 0
; CONFIG_BLOCK_END
M83
;LAYER_CHANGE
G1 X0 Y0 F9000
;TYPE:Support
G1 X1 Y0 E0.04 F1200
G1 X2 Y0 E0.04 F1200
G1 X3 Y0 E0.04 F1200
;TYPE:Internal infill
G1 X3 Y1 F9000
GCODE

set +e
ORCASLICER_CODEX_ARC_SUPPORT_NATIVE=1 \
  "$repo_root/scripts/orcaslicer_codex_arc_support_transform.py" \
  "$support_input" "$support_output" --audit "$support_audit"
support_status=$?
set -e
if [[ "$support_status" -eq 0 ]]; then
  echo "Support-only input must not pass the Arc Overhang transform" >&2
  exit 1
fi

python3 - "$support_output" "$support_audit" <<'PY'
import json
import pathlib
import sys

output_path = pathlib.Path(sys.argv[1])
audit_path = pathlib.Path(sys.argv[2])
audit = json.loads(audit_path.read_text(encoding="utf-8"))
output = output_path.read_text(encoding="utf-8")
if audit.get("status") != "failed":
    raise SystemExit("Support-only transform should fail")
if "normal support extrusion moves" not in str(audit.get("error", "")):
    raise SystemExit(f"Support-only transform failed for the wrong reason: {audit.get('error')}")
if ";TYPE:Arc support" in output or "; FEATURE: Arc support" in output:
    raise SystemExit("Support-only transform must not create Arc support output")
if audit.get("native_arc_support_enabled") is not False:
    raise SystemExit("Old native support conversion flag must not re-enable support output")
PY

cp "$support_input" "$support_adapter_input"
set +e
ORCASLICER_CODEX_ARC_SUPPORT_NATIVE=1 \
ORCASLICER_CODEX_ARC_SUPPORT_TRANSFORM="$repo_root/scripts/orcaslicer_codex_arc_support_transform.py" \
  "$repo_root/scripts/orcaslicer_codex_arc_support_inplace_adapter.py" \
  "$support_adapter_input"
support_adapter_status=$?
set -e
if [[ "$support_adapter_status" -eq 0 ]]; then
  echo "Adapter must not fall back to ordinary support material" >&2
  exit 1
fi

python3 - "$support_adapter_input" "$support_adapter_audit" <<'PY'
import json
import pathlib
import sys

gcode_path = pathlib.Path(sys.argv[1])
audit_path = pathlib.Path(sys.argv[2])
gcode = gcode_path.read_text(encoding="utf-8")
audit = json.loads(audit_path.read_text(encoding="utf-8"))
if audit.get("status") != "failed":
    raise SystemExit("Support adapter audit should record the failed transform")
if "fallback_normal_support_preserved" in gcode:
    raise SystemExit("Adapter preserved ordinary support fallback metadata")
if ";TYPE:Arc support" in gcode:
    raise SystemExit("Adapter converted support material into Arc support")
PY

python3 - "$repo_root" <<'PY'
import pathlib
import sys

repo_root = pathlib.Path(sys.argv[1])
required = {
    "src/libslic3r/GCode/PostProcessor.cpp": [
        "ORCASLICER_CODEX_ARC_SUPPORT_INPLACE_SCRIPT",
        "orcaslicer_codex_arc_support_inplace_adapter.py",
        "Arc Overhang selected",
    ],
    "src/libslic3r/GCode/GCodeProcessor.cpp": [
        "orcaslicer_codex_arc_support_",
        "tinmanx_arc_support_",
        "parse_arc_support_role_marker",
        "erBridgeInfill",
    ],
    "src/slic3r/GUI/BackgroundSlicingProcess.cpp": [
        "prepare_arc_support_preview_gcode",
        "reload_arc_support_preview_from_gcode",
    ],
    "src/slic3r/GUI/GCodeViewer.cpp": [
        "TinManX1 Arc Overhang",
        "Arc Overhang",
    ],
    "SoftFever_doc/orcaslicer_codex_feature_attribution.md": [
        "Kelsch OrcaSlicer integration",
        "GPL-3.0",
    ],
}
for relative, needles in required.items():
    text = (repo_root / relative).read_text(encoding="utf-8", errors="replace")
    for needle in needles:
        if needle not in text:
            raise SystemExit(f"{relative} missing {needle}")
if not (repo_root / "third_party/gpl/arc-overhang/LICENSE").exists():
    raise SystemExit("Vendored Arc Overhang GPL license is missing")
PY

echo "TinManX1 Arc Overhang runtime smoke passed"
